const prefersReducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const ro=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');e.target.querySelectorAll('.counter').forEach(startCounter)}}),{threshold:.18});
document.querySelectorAll('.reveal').forEach(el=>ro.observe(el));
const bo=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('in')}),{threshold:.42});
document.querySelectorAll('.watchbar').forEach(el=>bo.observe(el));
function startCounter(el){if(el.dataset.done)return;el.dataset.done='1';const target=Number(el.dataset.value),dec=Number(el.dataset.decimals||0);if(prefersReducedMotion){el.textContent=target.toLocaleString(undefined,{minimumFractionDigits:dec,maximumFractionDigits:dec});return}const start=performance.now(),dur=900;function f(now){const p=Math.min((now-start)/dur,1),ease=1-Math.pow(1-p,4),v=target*ease;el.textContent=v.toLocaleString(undefined,{minimumFractionDigits:dec,maximumFractionDigits:dec});if(p<1)requestAnimationFrame(f)}requestAnimationFrame(f)}
let modalReturnFocus=null;let pointerDownBackdrop=null;
function setArticleBackgroundInert(openModal=null){document.querySelectorAll('body > *').forEach(node=>{if(!(node instanceof HTMLElement)||node.tagName==='SCRIPT')return;node.inert=Boolean(openModal&&node!==openModal)})}
function modalFocusableElements(modal){return [...modal.querySelectorAll('a[href],button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(element=>!element.closest('[hidden]')&&element.getClientRects().length>0)}
function openArticleModal(trigger){const modal=document.getElementById(trigger.dataset.modal+'Modal');if(!modal)return;modalReturnFocus=trigger;modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setArticleBackgroundInert(modal);requestAnimationFrame(()=>modal.querySelector('[data-close]')?.focus())}
function closeModals(){const returnFocus=modalReturnFocus;document.querySelectorAll('.lesson-modal.open').forEach(modal=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});document.body.style.overflow='';setArticleBackgroundInert(null);modalReturnFocus=null;if(returnFocus?.isConnected)requestAnimationFrame(()=>returnFocus.focus())}
document.querySelectorAll('.info').forEach(btn=>btn.addEventListener('click',()=>openArticleModal(btn)));document.querySelectorAll('[data-close]').forEach(btn=>btn.addEventListener('click',closeModals));document.querySelectorAll('.lesson-modal').forEach(modal=>{modal.addEventListener('pointerdown',event=>{pointerDownBackdrop=event.target===modal?modal:null});modal.addEventListener('click',event=>{if(event.target===modal&&pointerDownBackdrop===modal)closeModals();pointerDownBackdrop=null})});document.addEventListener('pointercancel',()=>{pointerDownBackdrop=null},true);document.addEventListener('keydown',event=>{const modal=document.querySelector('.lesson-modal.open');if(!modal)return;if(event.key==='Escape'){event.preventDefault();closeModals();return}if(event.key!=='Tab')return;const focusable=modalFocusableElements(modal);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();return}if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();return}if(!modal.contains(document.activeElement)){event.preventDefault();(event.shiftKey?last:first).focus()}});
